services:

  App.Shared.LoggerConfig:
    factory:
      class: ../../../../../contexts/shared/infrastructure/logging/WinstonLoggerDevConfig
      method: 'config'
      arguments: [ ]

  App.Shared.Logger:
    class: ../../../../../contexts/shared/infrastructure/logging/WinstonLogger
    arguments: [ '@App.Shared.LoggerConfig' ]

  App.Shared.ErrorHandlerMiddleware:
    class: ../../../../../contexts/shared/infrastructure/express/middlewares/ErrorHandlerMiddleware
    arguments: [ '@App.Shared.Logger' ]

  App.Shared.EntityManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/mysql/ContextEntityManagerFactory
      method: 'create'
      arguments: [ ]
